"""Senza — oh-my-harness runtime Python SDK."""

from __future__ import annotations

from typing import Any, Callable, Iterator, Optional

# ── Version & utilities ──────────────────────────────────────────────────────

def version() -> str: ...
def to_json(obj: Any) -> str: ...
def from_json(json_str: str) -> Any: ...

# ── Provider ─────────────────────────────────────────────────────────────────

class Provider:
    """LLM provider handle (OpenAI-compatible or Anthropic)."""

def create_openai_provider(
    api_key: str,
    base_url: Optional[str] = ...,
    chat_path: Optional[str] = ...,
    thinking_scheme: Optional[str] = ...,
    parse_reasoning_content: bool = ...,
    tolerant_keepalive: bool = ...,
) -> Provider: ...

def create_anthropic_provider(
    api_key: str,
    base_url: Optional[str] = ...,
) -> Provider: ...

# ── Tool ─────────────────────────────────────────────────────────────────────

class ToolContext:
    """Context passed to a tool callback."""

class Tool:
    """A tool registered on a harness or workflow engine."""

def create_tool(
    name: str,
    description: str,
    parameters_schema: str,
    callback: Callable[..., Any],
) -> Tool: ...

def create_sync_tool(
    name: str,
    description: str,
    parameters_schema: str,
    callback: Callable[..., Any],
) -> Tool: ...

# ── Plugin ───────────────────────────────────────────────────────────────────

class Plugin:
    """A bundle of tools and hooks."""

def create_plugin(
    name: str,
    tools: Optional[list[Tool]] = ...,
    hooks: Optional[list[Hook]] = ...,
) -> Plugin: ...

# ── Hook (11 types) ──────────────────────────────────────────────────────────

class Hook:
    """Opaque hook wrapper."""

def create_before_turn_hook(callback: Callable[[dict], None]) -> Hook: ...
def create_after_turn_hook(callback: Callable[[dict], None]) -> Hook: ...
def create_before_run_hook(callback: Callable[[dict], None]) -> Hook: ...
def create_after_provider_response_hook(callback: Callable[[dict], None]) -> Hook: ...
def create_before_provider_request_hook(callback: Callable[[dict], None]) -> Hook: ...
def create_before_tool_call_hook(callback: Callable[[dict], Optional[str]]) -> Hook: ...
def create_after_tool_call_hook(callback: Callable[[dict], Any]) -> Hook: ...
def create_should_stop_hook(callback: Callable[[dict], bool]) -> Hook: ...
def create_before_compact_hook(callback: Callable[[dict], Any]) -> Hook: ...
def create_transform_context_hook(callback: Callable[[dict], dict]) -> Hook: ...
def create_prepare_next_turn_hook(callback: Callable[[dict], Optional[dict]]) -> Hook: ...

# ── Event channel (human-in-the-loop) ────────────────────────────────────────

class EventStreamHandle:
    """Handle for submitting external events."""

class WaitForExternalEventTool:
    """Tool that pauses the LLM to wait for an external event."""

def create_event_channel(task_id: str) -> tuple[EventStreamHandle, WaitForExternalEventTool]: ...

# ── Judge ────────────────────────────────────────────────────────────────────

class Judge:
    """Opaque judge wrapper (from create_judge)."""

def create_judge(callback: Callable[[dict], str]) -> Judge: ...

class CompositeJudge:
    """Per-step routing judge. Use create_composite_judge() to instantiate."""

    def on(self, step: str, callback: Callable[[dict], str]) -> None: ...
    def fallback(self, callback: Callable[[dict], str]) -> None: ...

def create_composite_judge() -> CompositeJudge: ...

# ── Executor ─────────────────────────────────────────────────────────────────

class Executor:
    """Opaque executor wrapper."""

def create_executor(callback: Callable[[dict], dict]) -> Executor: ...
def create_shell_executor(
    commands: list[str],
    default_timeout_ms: int = ...,
    max_output_bytes: int = ...,
) -> Executor: ...
def create_http_executor(
    allowed_hosts: list[str],
    allowed_schemes: Optional[list[str]] = ...,
    max_timeout_ms: int = ...,
    allow_private_ip_targets: bool = ...,
) -> Executor: ...

# ── Agent layer: HarnessBuilder ──────────────────────────────────────────────

class HarnessBuilder:
    """Fluent builder for AgentHarness."""

    def __init__(self, model: str) -> None: ...

    def provider(self, pattern: str, provider: Provider) -> HarnessBuilder: ...
    def system_prompt(self, prompt: str) -> HarnessBuilder: ...
    def max_tokens(self, tokens: int) -> HarnessBuilder: ...
    def temperature(self, temp: Optional[float]) -> HarnessBuilder: ...
    def thinking_level(self, level: str) -> HarnessBuilder: ...
    def tool(self, tool: Tool) -> HarnessBuilder: ...
    def plugin(self, plugin: Plugin) -> HarnessBuilder: ...
    def auto_compact(self, enabled: bool) -> HarnessBuilder: ...
    def compaction_reserve_tokens(self, tokens: Optional[int]) -> HarnessBuilder: ...
    def compaction_keep_recent_tokens(self, tokens: Optional[int]) -> HarnessBuilder: ...

    def build(self) -> AgentHarness: ...

# ── Agent layer: AgentHarness ────────────────────────────────────────────────

class HarnessEventIterator:
    """Iterator over agent events (text_delta, tool_call_start, etc.)."""

class AgentHarness:
    """Single-agent LLM harness with tool calling and streaming."""

    # ── Prompting ──
    def prompt(self, text: str) -> None: ...
    def prompt_and_collect(self, text: str, timeout_ms: int = ...) -> list[dict]: ...
    def collect_until_settled(self, timeout_ms: int = ...) -> list[dict]: ...
    def events(self, timeout_ms: int = ...) -> HarnessEventIterator: ...
    def abort(self) -> None: ...

    # ── Dynamic config ──
    def set_model(
        self, model: str,
        context_window: Optional[int] = ...,
        max_tokens: Optional[int] = ...,
    ) -> None: ...
    def set_system_prompt(self, prompt: Optional[str] = ...) -> None: ...
    def set_temperature(self, temperature: Optional[float] = ...) -> None: ...
    def set_thinking_level(self, level: str) -> None: ...
    def set_max_tokens(self, max_tokens: int) -> None: ...
    def set_tools(self, tools: list[Tool]) -> None: ...
    def set_active_tools(self, tools: Optional[list[str]] = ...) -> None: ...

    # ── Steering ──
    def steer(self, text: str) -> None: ...
    def follow_up(self, text: str) -> None: ...
    def next_turn(self, text: str) -> None: ...
    def continue_run(self) -> None: ...

    # ── Queue management ──
    def clear_steering_queue(self) -> None: ...
    def clear_follow_up_queue(self) -> None: ...
    def clear_all_queues(self) -> None: ...
    def has_queued_messages(self) -> bool: ...

    # ── Inspection ──
    def get_messages(self) -> list[dict]: ...
    def last_response(self) -> str: ...
    def message_count(self) -> int: ...
    def phase(self) -> str: ...
    def usage(self) -> dict: ...
    def reset_usage(self) -> None: ...

    # ── Waiting ──
    def wait_for_idle(self) -> None: ...
    def wait_for_settled(self) -> None: ...

    # ── Session / Branch ──
    def fork_branch(self, from_entry: str, label: Optional[str] = ...) -> str: ...
    def navigate_tree(self, target: str) -> None: ...
    def list_branches(self) -> list[dict]: ...
    def read_active_path(self) -> list[dict]: ...
    def read_all_entries(self) -> list[dict]: ...
    def delete_branch(self, leaf: str) -> None: ...
    def generate_branch_summary(self, leaf: str) -> dict: ...

    # ── Context manager ──
    def __enter__(self) -> AgentHarness: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...

# ── Runtime layer: WorkflowEngine ────────────────────────────────────────────

class WorkflowEventIterator:
    """Iterator over workflow events (step_started, step_finished, etc.)."""

class WorkflowEngine:
    """Multi-step workflow engine with conditional routing and crash recovery."""

    def __init__(
        self,
        workflow_dict: dict,
        provider: Provider,
        model: str,
        judge: Judge | CompositeJudge,
        session_base_dir: str = ...,
    ) -> None: ...

    @classmethod
    def restore(
        cls,
        task_store_dir: str,
        task_id: str,
        provider: Provider,
        model: str,
        judge: Judge | CompositeJudge,
        session_base_dir: str = ...,
    ) -> WorkflowEngine: ...

    # ── Registration (chainable) ──
    def with_tool(self, tool: Tool) -> WorkflowEngine: ...
    def with_external_tool(self, tool: WaitForExternalEventTool) -> WorkflowEngine: ...
    def with_executor(self, name: str, executor: Executor) -> WorkflowEngine: ...
    def with_hooks(self, hooks_list: list[Hook]) -> WorkflowEngine: ...
    def with_step_plugin(self, step_id: str, plugin: Plugin) -> WorkflowEngine: ...
    def with_task_store(self, dir: str) -> WorkflowEngine: ...
    def with_max_tokens(self, max_tokens: Optional[int] = ...) -> WorkflowEngine: ...
    def with_max_steps(self, max: int) -> WorkflowEngine: ...
    def with_max_retries(self, max: int) -> WorkflowEngine: ...

    # ── Context ──
    def set_context_variable(self, key: str, value: Any) -> None: ...
    def get_context_variable(self, key: str) -> Any: ...

    # ── Execution ──
    def run(self) -> None: ...
    def pause(self, reason: str) -> None: ...
    def resume(self) -> None: ...
    def cancel(self, reason: str) -> None: ...

    # ── Inspection ──
    def state(self) -> str: ...
    def current_step(self) -> Optional[str]: ...
    def step_history(self) -> list[dict]: ...
    def task_id(self) -> str: ...
    def total_cost(self) -> dict: ...
    def checkpoint(self, description: str, payload: Any) -> None: ...
    def subscribe(self, timeout_ms: int = ...) -> WorkflowEventIterator: ...

    # ── Context manager ──
    def __enter__(self) -> WorkflowEngine: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...

# ── Misc classes (opaque wrappers) ───────────────────────────────────────────

class Agent:
    """Agent (test-utils only)."""

class EventIterator:
    """Generic event iterator."""
